/*
 * Copyright 2007 Sun Microsystems, Inc. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa Clara,
 * CA 95054 USA or visit www.sun.com if you need additional information or
 * have any questions.
 *
 */
package gchisto2.gui.panels.gcdata;

import gchisto2.gcactivity.GcActivity;
import gchisto2.gcactivity.GcActivitySet;
import gchisto2.gctrace.GcTrace;
import gchisto2.gctrace.GcTraceCheckpoint;
import gchisto2.gctrace.RcWithGcTraceCheckpoint;
import gchisto2.gctrace.GcTraceListener;
import gchisto2.gctrace.RcWithGcTraceCheckpointCallback;
import gchisto2.utils.Locker;
import gchisto2.utils.Refresher;
import gchisto2.utils.WorkerThread;
import gchisto2.utils.errorchecking.ArgumentChecking;

/**
 *
 * @author  tony
 */
public class DataPanel extends javax.swing.JPanel
        implements GcTraceListener, RcWithGcTraceCheckpointCallback {

    final private GcTrace gcTrace;
    final private Refresher refresher;
    final private Locker locker = new Locker();

    String getString(GcActivity gcActivity) {
        return String.format("%20s %12.4f %12.6f\n",
                gcActivity.getName(),
                gcActivity.getStartSec(),
                gcActivity.getDurationSec());
    }

    private void updateTextArea(int from, int to) {
        GcActivitySet allGcActivities = gcTrace.getAllGcActivities();
        StringBuilder strBuilder = new StringBuilder();
        for (int i = from; i < to; ++i) {
            GcActivity gcActivity = allGcActivities.get(i);
            String str = getString(gcActivity);
            strBuilder.append(str);
        }
        textArea.append(strBuilder.toString());
    }

    @Override
    public void refresh(GcTraceCheckpoint checkpoint) {
        int from = checkpoint.prevAllGcActivitiesSize();
        int to = checkpoint.allGcActivitiesSize();
        updateTextArea(from, to);
    }

    public void possiblyRefresh() {
        refresher.possiblyRefresh();
    }

    @Override
    public void gcActivityAdded(
            GcTrace gcTrace,
            GcActivitySet gcActivitySet,
            GcActivity gcActivity) {
        assert gcTrace == this.gcTrace;
        possiblyRefresh();
    }

    @Override
    public void gcActivityNameAdded(
            GcTrace gcTrace,
            int id,
            String gcActivityName) {
    }

    DataPanel(GcTrace gcTrace) {
        ArgumentChecking.notNull(gcTrace, "gcTrace");

        this.gcTrace = gcTrace;
        GcTraceCheckpoint checkpoint = new GcTraceCheckpoint(gcTrace);
        this.refresher = new Refresher(
                WorkerThread.instance(),
                new RcWithGcTraceCheckpoint(checkpoint, locker, this));
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAreaPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        textArea.setColumns(20);
        textArea.setRows(5);
        textAreaPane.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textAreaPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textAreaPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea textArea;
    private javax.swing.JScrollPane textAreaPane;
    // End of variables declaration//GEN-END:variables
}
